apiVersion: v1
kind: Service
metadata:
  name: helm-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: helm-app
